package geminiresponsename

const Input                     = "INPUT"
const SensitiveInput            = "SENSITIVE INPUT"
const Success                   = "SUCCESS"
const RedirectTemporary         = "REDIRECT - TEMPORARY"
const RedirectPermanent         = "REDIRECT - PERMANENT"
const TemporaryFailure          = "TEMPORARY FAILURE"
const ServerUnavailable         = "SERVER UNAVAILABLE"
const CGIError                  = "CGI ERROR"
const ProxyError                = "PROXY ERROR"
const SlowDown                  = "SLOW DOWN"
const PermanentFailure          = "PERMANENT FAILURE"
const NotFound                  = "NOT FOUND"
const Gone                      = "GONE"
const ProxyRequestRefused       = "PROXY REQUEST REFUSED"
const BadRequest                = "BAD REQUEST"
const ClientCertificateRequired = "CLIENT CERTIFICATE REQUIRED"
const CertificateNotAuthorised  = "CERTIFICATE NOT AUTHORISED"
const CertificateNotValid       = "CERTIFICATE NOT VALID"
